from pathlib import Path

p = Path('night.py')
s = p.read_text()

anchor = '''    def _on_route_added(self, route: Route):\n'''
insert = '''    def _compile_route_invoker(self, route: Route, plan: _EndpointPlan):\n        fn = route.endpoint\n        coerce = self._coerce_response\n        kind = route._night_call_kind\n\n        if kind == ROUTE_CALL_DIRECT_PARAM:\n            name = route._night_direct_param\n            if plan.is_coro:\n                async def invoke(req, params, _fn=fn, _name=name, _coerce=coerce):\n                    return _coerce(await _fn(params[_name]))\n            else:\n                async def invoke(req, params, _fn=fn, _name=name, _coerce=coerce):\n                    return _coerce(_fn(params[_name]))\n            return invoke\n\n        if kind == ROUTE_CALL_NOARGS:\n            if plan.is_coro:\n                async def invoke(req, params, _fn=fn, _coerce=coerce):\n                    return _coerce(await _fn())\n            else:\n                async def invoke(req, params, _fn=fn, _coerce=coerce):\n                    return _coerce(_fn())\n            return invoke\n\n        if kind == ROUTE_CALL_REQUEST_KEYWORD:\n            if plan.is_coro:\n                async def invoke(req, params, _fn=fn, _coerce=coerce):\n                    return _coerce(await _fn(req=req))\n            else:\n                async def invoke(req, params, _fn=fn, _coerce=coerce):\n                    return _coerce(_fn(req=req))\n            return invoke\n\n        if kind == ROUTE_CALL_REQUEST_POSITIONAL:\n            if plan.is_coro:\n                async def invoke(req, params, _fn=fn, _coerce=coerce):\n                    return _coerce(await _fn(req))\n            else:\n                async def invoke(req, params, _fn=fn, _coerce=coerce):\n                    return _coerce(_fn(req))\n            return invoke\n\n        async def invoke(req, params, _route=route):\n            return await self._call_route_generic(_route, req, params)\n        return invoke\n\n'''
if anchor not in s:
    raise SystemExit('on_route_added anchor missing')
s = s.replace(anchor, insert + anchor, 1)

# Compile the invoker immediately after route classification in both dynamic and static paths.
s = s.replace(
'''            self._classify_route_call(route, plan)\n            return\n\n        self._classify_route_call(route, plan)\n        self._static_route_index.setdefault(key, []).append(route)\n''',
'''            self._classify_route_call(route, plan)\n            route._night_invoke = self._compile_route_invoker(route, plan)\n            return\n\n        self._classify_route_call(route, plan)\n        route._night_invoke = self._compile_route_invoker(route, plan)\n        self._static_route_index.setdefault(key, []).append(route)\n''', 1)

old = '''    async def _call_route(self, route: Route, req: Request, params: dict[str, t.Any]) -> Response:\n        plan = route._night_plan\n        fn = route.endpoint\n        kind = route._night_call_kind\n\n        if kind == ROUTE_CALL_DIRECT_PARAM:\n            result = fn(params[route._night_direct_param])\n        elif kind == ROUTE_CALL_NOARGS:\n            result = fn()\n        elif kind == ROUTE_CALL_REQUEST_KEYWORD:\n            result = fn(req=req)\n        elif kind == ROUTE_CALL_REQUEST_POSITIONAL:\n            result = fn(req)\n        else:\n            kwargs = params\n\n            if plan.body_model is not None:\n                payload = await req.json()\n                validated = _validate_dataclass(plan.body_model, payload)\n                target = next((name for name in plan.body_candidates if name not in kwargs), None)\n                if target is not None:\n                    kwargs[target] = validated\n                else:\n                    kwargs.setdefault("data", validated)\n\n            if plan.call_mode == CALL_REQUEST_KEYWORD:\n                result = fn(req=req, **kwargs)\n            elif plan.call_mode == CALL_REQUEST_POSITIONAL:\n                result = fn(req, **kwargs)\n            elif kwargs:\n                result = fn(**kwargs)\n            else:\n                result = fn()\n\n        if plan.is_coro:\n            result = await t.cast(t.Awaitable, result)\n        return self._coerce_response(result)\n'''
new = '''    async def _call_route_generic(self, route: Route, req: Request, params: dict[str, t.Any]) -> Response:\n        plan = route._night_plan\n        fn = route.endpoint\n        kwargs = params\n\n        if plan.body_model is not None:\n            payload = await req.json()\n            validated = _validate_dataclass(plan.body_model, payload)\n            target = next((name for name in plan.body_candidates if name not in kwargs), None)\n            if target is not None:\n                kwargs[target] = validated\n            else:\n                kwargs.setdefault("data", validated)\n\n        if plan.call_mode == CALL_REQUEST_KEYWORD:\n            result = fn(req=req, **kwargs)\n        elif plan.call_mode == CALL_REQUEST_POSITIONAL:\n            result = fn(req, **kwargs)\n        elif kwargs:\n            result = fn(**kwargs)\n        else:\n            result = fn()\n\n        if plan.is_coro:\n            result = await t.cast(t.Awaitable, result)\n        return self._coerce_response(result)\n\n    async def _call_route(self, route: Route, req: Request, params: dict[str, t.Any]) -> Response:\n        invoke = getattr(route, "_night_invoke", None)\n        if invoke is None:\n            # Compatibility path for synthetic routes used by _call_endpoint().\n            return await self._call_route_generic(route, req, params)\n        return await invoke(req, params)\n'''
if old not in s:
    raise SystemExit('call_route anchor missing')
s = s.replace(old, new, 1)

# Avoid two empty async hook calls on the overwhelmingly common no-hook path.
s = s.replace(
'''    async def _dispatch(self, req: Request) -> Response:\n        early = await self._run_before_hooks(req)\n        if early is not None:\n            return early\n\n        route, params = self._match_method(req.path, req.method)\n        req.path_params = params\n        resp = await self._call_route(route, req, params)\n        resp = await self._run_after_hooks(req, resp)\n        return resp\n''',
'''    async def _dispatch(self, req: Request) -> Response:\n        if self.before_hooks:\n            early = await self._run_before_hooks(req)\n            if early is not None:\n                return early\n\n        route, params = self._match_method(req.path, req.method)\n        req.path_params = params\n        resp = await route._night_invoke(req, params)\n        if self.after_hooks:\n            resp = await self._run_after_hooks(req, resp)\n        return resp\n''', 1)

p.write_text(s)
